apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment-blue  # Use a distinct name for the blue deployment
  labels:
    app: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
      harness.io/color: blue  # Label for the blue version of the service
  template:
    metadata:
      labels:
        app: my-app
        harness.io/color: blue  # Label for the blue version of the service
    spec:
      containers:
        - name: my-app
          image: "nasi101/tetris"  # Replace with your image
          ports:
            - containerPort: 8080
