apiVersion: v1
kind: Service
metadata:
  name: my-app-service12-blue  # Use a distinct name for the blue service
  labels:
    harness.io/color: blue  # Label for the blue service
spec:
  selector:
    app: my-app
    harness.io/color: blue  # Select the blue deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
  type: LoadBalancer  # Exposes the app to external traffic
