apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app-deployment
  namespace: autopilot-cluster-sm
  labels:
    app: demo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
        - name: demo-app
          image: "padmaraouppuluri/padmaraodocker:image"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          command: ["java", "-jar", "app.jar"]  # Ensure app.jar is in the container

          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
              ephemeral-storage: "500Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
              ephemeral-storage: "1Gi"

          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10

      imagePullSecrets:
        - name: regcred
