---
- name: Deploy Dockerized Application
  hosts: localhost
  become: yes
  tasks:
    - name: Ensure Docker is installed
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Ensure Docker service is running
      service:
        name: docker
        state: started
        enabled: yes

    - name: Pull Docker image
      community.docker.docker_image:
        name: "{{ docker_image }}"
        source: pull

    - name: Stop and remove existing container (if running)
      community.docker.docker_container:
        name: demo-app
        state: absent

    - name: Run Docker container
      community.docker.docker_container:
        name: demo-app
        image: "{{ docker_image }}"
        state: started
        ports:
          - "8082:8080"
