---
- name: Deploy Dockerized Application
  hosts: localhost
  become: yes
  tasks:
    - name: Update APT cache
      apt:
        update_cache: yes

    - name: Install required packages for Docker
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present

    - name: Ensure /etc/apt/keyrings directory exists
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Remove old Docker GPG key
      file:
        path: /etc/apt/keyrings/docker.gpg
        state: absent

    - name: Add Docker GPG key
      shell: |
        curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
        chmod a+r /etc/apt/keyrings/docker.gpg
      args:
        executable: /bin/bash

    - name: Add Docker repository
      shell: |
        echo "deb [signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
      args:
        executable: /bin/bash

    - name: Update APT cache again
      apt:
        update_cache: yes
      retries: 3
      delay: 10
      register: result
      until: result is succeeded

    - name: Install Docker
      apt:
        name: docker-ce
        state: present

    - name: Ensure Docker service is running
      service:
        name: docker
        state: started
        enabled: yes

    - name: Log in to Docker Hub
      shell: echo "dckr_pat_9Y0QPnZZd0mD0SxMSrusUrDJgVc" | docker login -u padmaraouppuluri --password-stdin
      no_log: true

    - name: Build Docker image
      command: docker build -t padmaraouppuluri/padmaraodocker:latest .
      args:
        chdir: /home/padmaraodevops/my-docker-app

    - name: Pull Docker image
      command: docker pull padmaraouppuluri/padmaraodocker:image

    - name: Stop and remove any existing container
      shell: |
        docker stop padmarao_container || true
        docker rm padmarao_container || true
      ignore_errors: yes

    - name: Run Docker container
      command: docker run -d --name padmarao_container -p 8082:8080 padmaraouppuluri/padmaraodocker:image
