apiVersion: v1
kind: Service
metadata:
  name: my-app-service12-stage
  labels:
    harness.io/color: green  # Label for the green service
  annotations:
    harness.io/direct-apply: "true"  # Direct apply for green service (bypasses Blue/Green workflow)
spec:
  selector:
    app: my-app
    harness.io/color: green  # Select the green deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
  type: LoadBalancer  # Exposes the app to external traffic
