apiVersion: v1
kind: Service
metadata:
  name: my-app-service12-green  # Unique name for the green service
  labels:
    harness.io/color: green  # Label to differentiate the green version
spec:
  selector:
    app: my-app
    harness.io/color: green  # Ensure this matches the label in your green deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
  type: LoadBalancer  # Exposes the app to external traffic
