apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment-stage
  labels:
    app: my-app
  annotations:
    harness.io/direct-apply: true  # This annotation ensures direct apply for the green deployment (bypasses Blue/Green workflow)
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
        harness.io/color: green  # Label for the green version of the service
    spec:
      containers:
        - name: my-app
          image: "nasi101/tetris"  # Update to your specific image if necessary
          ports:
            - containerPort: 8080
